### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by HaddedMohamed** [bguillouet/traj-dist#16]
**Hey guys, I have a problem when running the command line pip install , it gets me these errors:**

ERROR: Exception:
Traceback (most recent call last):
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, inwrapper
    return func(self, options, args)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 100, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 301, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 300, in __init__
    super().__init__(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 457,in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 500,in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 66, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 39,in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 97,in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 177, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in_build_backend
    obj = import_module(mod_path)
  File "/home/jovyan/anaconda3/envs/pytorch_vn/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

**Thank you for your help.**

**Comment by jiaoleixin** [comment]
+1. but when I use "pip list", there shows setuptools has already been installed and its version is also satisfied.

**Comment by jiaoleixin** [comment]
+1. but when I use "pip list", there shows setuptools has already been installed and its version is also satisfied.

**Comment by glsaltfish** [comment]
I guess the problem may be that the package is installed in our base environment by default. To ignore the error because it is already installed or try to update the setuptools in the base environment, hope it helps.

**Comment by myradio** [comment]
In my case it worked after editing the _pyproject.toml_
Current version only lists `Cython `as requirement. 

I changed it to the following:

```
> [build-system]
> requires = ["setuptools", "wheel","Cython>=0.27.3", "numpy"]
> build-backend = "setuptools.build_meta" 
```

I did not include numpy first, but I was getting the module not found error for numpy instead of setuptools.

**Comment by 0815Teresa** [comment]
**I also have this problem when running the command line pip install.**

ERROR: Exception:
Traceback (most recent call last):
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 401, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 493, in collect_root_requirements
    requested_extras=(),
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 458, in _make_requirement_from_install_req
    version=None,
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    version=version,
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    version=version,
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 582, in _prepare_linked_requirement
    self.check_build_deps,
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 70, in _get_prepared_distribution
    finder, build_isolation, check_build_deps
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 174, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

I wonder how to fix it. Thank u.

**Comment by 0815Teresa** [comment]
**pip install traj-dist, import traj_dist is right, but import traj_dist.distance is wrong.**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/limengqiu/.conda/envs/lmq1/lib/python3.7/site-packages/traj_dist/distance.py", line 1, in <module>
    from pydist.linecell import trajectory_set_grid
ModuleNotFoundError: No module named 'pydist'

I wanna ask u guys how to fix it. Thank u!
