### ISSUE TITLE
ModuleNotFoundError: No module named 'cydist.sspd' with Python 3

### ISSUE THREAD

**Issue by rpelorosso** [bguillouet/traj-dist#2]
Hi! I'm trying to run the examples using python 3, and I'm getting the following error:

```
[silencer@myhostname traj_dist]$ python example.py 
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    import traj_dist.distance as tdist
  File "/usr/lib/python3.6/site-packages/traj_dist/distance.py", line 3, in <module>
    from cydist.sspd import c_e_sspd, c_g_sspd
ModuleNotFoundError: No module named 'cydist.sspd'
```

I have installed it as per the readme file. It is working in python 2, however.

Do you have any idea about what could be happening? I'd like to use this library with python 3.

Thank you for your hard work!
Rodrigo

**Comment by djjavo** [comment]
> Hi! I'm trying to run the examples using python 3, and I'm getting the following error:
> 
> ```
> [silencer@myhostname traj_dist]$ python example.py 
> Traceback (most recent call last):
>   File "example.py", line 2, in <module>
>     import traj_dist.distance as tdist
>   File "/usr/lib/python3.6/site-packages/traj_dist/distance.py", line 3, in <module>
>     from cydist.sspd import c_e_sspd, c_g_sspd
> ModuleNotFoundError: No module named 'cydist.sspd'
> ```
> 
> I have installed it as per the readme file. It is working in python 2, however.
> 
> Do you have any idea about what could be happening? I'd like to use this library with python 3.
> 
> Thank you for your hard work!
> Rodrigo

Hi Rodrigo, if you are still interested in using this, I have it working on Python 3.6. Either check out the pull request, or my [fork of this repository](https://github.com/djjavo/traj-dist).
